"""removed qstn hdr attempt date id

Revision ID: 4628736f752e
Revises: 877bcdb1411c
Create Date: 2022-01-30 13:06:43.646625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4628736f752e'
down_revision = '877bcdb1411c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_attempt_response_ibfk_2', 'question_attempt_response', type_='foreignkey')
    op.drop_column('question_attempt_response', 'questions_attempt_hdr_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_attempt_response', sa.Column('questions_attempt_hdr_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('question_attempt_response_ibfk_2', 'question_attempt_response', 'question_attempt_hdr', ['questions_attempt_hdr_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
