"""second migration

Revision ID: 877bcdb1411c
Revises: c1fa88d5451f
Create Date: 2022-01-30 12:51:33.470372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877bcdb1411c'
down_revision = 'c1fa88d5451f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_attempt_response', sa.Column('attempt_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_attempt_response', 'attempt_date')
    # ### end Alembic commands ###
