"""Initial migration

Revision ID: c1fa88d5451f
Revises: 
Create Date: 2022-01-30 12:48:57.879754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1fa88d5451f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'question_attempt_response', 'question_options', ['question_option_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_attempt_response', type_='foreignkey')
    # ### end Alembic commands ###
