"""Initial migration.

Revision ID: f3091b3ed1ae
Revises: 
Create Date: 2022-02-23 14:58:08.263216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3091b3ed1ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_attempt_hdr',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(length=128), nullable=True),
    sa.Column('value', sa.Text(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_set',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('questionSet_title', sa.Text(length=128), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('questSetStatusID2RefData', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questSetStatusID2RefData'], ['reference_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.Text(length=128), nullable=True),
    sa.Column('question_type', sa.Text(length=128), nullable=True),
    sa.Column('questStatusID2RefData', sa.Integer(), nullable=True),
    sa.Column('question2QuestionSet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questStatusID2RefData'], ['reference_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question2QuestionSet'], ['question_set.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_option', sa.Text(), nullable=True),
    sa.Column('questionOption2Question', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questionOption2Question'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_attempt_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response_text', sa.Text(length=128), nullable=True),
    sa.Column('responseID2QuestionOptions', sa.Integer(), nullable=True),
    sa.Column('questionID2Questions', sa.Integer(), nullable=True),
    sa.Column('response2QuestionAttempt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questionID2Questions'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response2QuestionAttempt'], ['question_attempt_hdr.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responseID2QuestionOptions'], ['question_options.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_attempt_response')
    op.drop_table('question_options')
    op.drop_table('questions')
    op.drop_table('question_set')
    op.drop_table('reference_data')
    op.drop_table('question_attempt_hdr')
    # ### end Alembic commands ###
